dist: bionic
language: python
install:
  - pip install slackclient
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
script:
  - pytest
deploy:
  provider: pypi
  user: nicklambourne
  password:
    secure: q9CIElEMRtITkDt8OKJXADPvOPHMTGqtK73BU2bWLJyxZ00aGrqe+ObSjVMXqHe6C4/AhHR5Cl6PLggJyxJ/t5hLdfCZmdzH/z85osGortxoQUPy5jaQsNP+N6oc9raqHjvv8W83HkfzPG8+YY9IZ1woGOpgLe2ZFtE0ZOjdJ4voSkxo+jQ61f/DeYNvCWqXFwkGfs4bUdSbYIP5QtrxiiCivFEvYx9AyXig0CIvlNSUD5G0WHZlMjnuyk1BZ8INERTw9hc5ZydvakUW58DWqYr+AkRFjTkzjOfDgjRbJibvX65NMUfPQNqmyvKwWNJytk0fx1hFgTKcnU2oirjZM4zDVx9Yvsw6cER717Ky6xfBxj80R95AzCDKLJqJc50gr4/yWK0rXMjXVkSdL1dg0C5B6WBoMFhkw6XcuemYmKwYt4tTmDlu2NyCJxhDRkqFmQcNlaGmlvfyJzvNyEJrLYJjb8r56FLjQ5yFBITPH+pcQwoimfhixsdwcAUdxFquuU+Rr35SQHOJH6aMk5inHPT/L3B2TLIXNpP2gv6pimDp4w6KOZymNvHaCkyIMInwgSDiL1TzH/FC70XauzTTrcGTkp+Z53DUMvaJi49tjUYXr48za6I+9UBjv5Ohp+kCpod0OspMjcS12fCNNdAoZNX3O9HAllkT9jcEgtPR5Us=
  distributions: "sdist bdist_wheel"
  skip_existing: true
